import { StyleSheet } from "react-native-web";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E5EBEA',
  },
  header: {
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'left',
    backgroundColor: '#B098A4',
    padding: 45,
    color: 'black',
    marginBottom: 30,
  },
  title: {
    fontSize: 50,
    color: '#2C2C2C',
    textAlign: 'center',
    fontWeight: 'bold',
    marginBottom: 30,
  },
  buttonContainer: {
    margin: 50,
    marginTop: 60,
    borderRadius: 9,
    justifyContent: 'center',
  },
  button: {
    backgroundColor: '#2C2C2C',
    borderRadius: 8,
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    marginBottom: 35,
  },
  buttonText: {
    color: '#E5EBEA',
    fontSize: 28,
    fontWeight: 'bold',
  },
  buttonPressed: {
    backgroundColor: '#7B8C7C',
  },
  navBar: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: '#45503B',
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 55,
  },
  navText: {
    fontSize: 16,
    color: '#cfcfcf',
    fontWeight: 'bold',
  },
  goalsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  goalsStacked: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  centeredGoalContainer: {
    width: '80%',
    marginBottom: 20,
    alignItems: 'center',
  },
  divider: {
    height: 1,
    backgroundColor: '#ddd',
    marginVertical: 10,
  },
  goalContainer: {
    width: '30%',
    marginBottom: 20,
    alignItems: 'center',
  },
  goalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
    color: '#2C2C2C',
  },
  Total: {
    fontSize: 16,
    marginBottom: 10,
    textAlign: 'center',
    color: '#2C2C2C',
  },
  boxPlot: {
    width: '50%',
    height: 200,
    backgroundColor: '#e0e0e0',
    borderRadius: 5,
    marginBottom: 10,
    alignSelf: 'center',
  },
  progressBar: {
    width: '100%',
    backgroundColor: '#5F8575',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    position: 'absolute',
    bottom: 0,
  },
  progressText: {
    color: 'white',
    fontWeight: 'bold',
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -25 }, { translateY: -10 }],
  },
  input: {
    height: 40,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    padding: 20,
    marginBottom: 20,
    fontSize: 16,
    backgroundColor: '#FFF',
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    width: 300,
    minHeight: 500,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalTitle: {
    marginBottom: 15,
    textAlign: "center",
    fontSize: 18,
    fontWeight: 'bold',
  },
  modalSubtitle: {
    marginBottom: 15,
    textAlign: "center",
    fontSize: 15,
    fontWeight: 'bold',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  label: {
    fontWeight: 'bold',
    fontSize: 22,
    textAlign: 'center',
    marginTop: 75,
    marginBottom: 40,
    color: '#333',
  },
  summaryContainer: {
    marginTop: 20,
    alignItems: 'center',
  },
  summaryCaption: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  summaryText: {
    fontSize: 18,
    marginBottom: 5,
    textAlign: 'center',
    color: '#555',
  },
  navButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 20,
    width: '100%',
  },
  nextButton: {
    marginLeft: 'auto',
  },
});

export default styles;
